### PR TITLE
[COM-217] Abstract user CRUD operations to User Repository

### PR DESCRIPTION
**Pull request by dvillavicencio**
Created  a new user repository with the logic implemented in the `VendiaClient.java` class.

### CODE REVIEW

**Comment by rramsdany** [comment]
Unless I'm blind, this PR is showing 0 files changed?

**Review by dkaercher — APPROVED** [review]

**Comment by dvillavicencio** [comment]
You're absolutely right lol I need to see what's up with that

**Comment by Matt-Crow** [comment]
> Unless I'm blind, this PR is showing 0 files changed?

If I had to guess, it's because the PR is merging `main` into another branch, rather than the typical way. We don't have to code review when merging from `main`, just when we're merging into it

**Comment by dvillavicencio** [comment]
Imma close this, I lost track of the branches im working on and this just didn't have any changes lol

**Pull request closed without merging**
